### ISSUE TITLE
We can't do it alone ... 

### ISSUE THREAD

**Issue by i-marsh** [i-marsh/earth#2]
Trying to save the world alone would be a suicide mission, we really should put a team together
To fix this we could execute a recruitment drive and reach out to super heroes and talented individuals

maybe try : 
 - [x] spiderman he has a cool suit too
 - [ ]  ironman
 - [x] ~~wonder-woman~~
 - [x] ~~super-ted~~

**Comment by i-marsh** [comment]
you can't cross-over marvel and dc ☹️ 
and who's super-ted?

**Comment by i-marsh** [comment]
Good point, I'll update the list (cross them off) 
superted 

![image](https://user-images.githubusercontent.com/35036892/40096264-13a6b69a-589e-11e8-8d53-afa9f9b7f9bd.png)

he's awesome .. if a little fluffy ... 🐻

**Comment by i-marsh** [comment]
not enough players on the team ... and where is superted

**Comment by vaibssingh** [comment]
What is going on here? :rofl:

**Comment by i-marsh** [comment]
hahaha ... this was me messing around - showing how you can use GitHub :octocat: to save-the-universe ... doesn't have to be code :-) @vaibssingh - just having sum fun with my day job..
